version: "3"
services:
  postgres:
    image: postgres:9.6
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/:/docker-entrypoint-initdb.d/
    expose:
      - 5431
    ports:
      - "5431:5432"
    environment:
      - PGDATA= /var/lib/postgresql/data/db-files
      - POSTGRES_PASSWORD=local
      - POSTGRES_USER=local

      ##- POSTGRES_DB=testdb
    restart: unless-stopped

  adminer:
    image: "adminer"
    network_mode: bridge
    container_name: "adminer"
    restart: "always"
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  # APP*****************************************
  springbootapp:
    image: parking-mgmt:latest
    network_mode: bridge
    container_name: parking-mgmt
    expose:
      - 8080
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgres-data: